language: objective-c
osx_image: xcode7.3
xcode_project: BlueFoundation.xcodeproj
xcode_scheme: BlueFoundation
script:
- xctool -workspace BlueFoundation.xcworkspace -scheme BlueFoundation build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- xctool -workspace BlueFoundation.xcworkspace -scheme BlueFoundation build test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
- bash <(curl -s https://codecov.io/bash)
